// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package litedb

type Templates struct {
	ID        int64
	Namespace string
	Name      string
	Content   []byte
	CreatedAt string
	UpdatedAt string
}
