// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package litedb

import (
	"context"
)

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE
FROM templates
WHERE namespace = ?
  AND name = ?
`

type DeleteTemplateParams struct {
	Namespace string
	Name      string
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTemplate, arg.Namespace, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTemplateContent = `-- name: GetTemplateContent :one
SELECT content
FROM templates
WHERE namespace = ?
  AND name = ?
`

type GetTemplateContentParams struct {
	Namespace string
	Name      string
}

func (q *Queries) GetTemplateContent(ctx context.Context, arg GetTemplateContentParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getTemplateContent, arg.Namespace, arg.Name)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT name
FROM templates
WHERE namespace = ?
ORDER BY name
`

func (q *Queries) ListTemplates(ctx context.Context, namespace string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const templateExists = `-- name: TemplateExists :one
SELECT EXISTS (SELECT 1 FROM templates WHERE namespace = ? AND name = ?)
`

type TemplateExistsParams struct {
	Namespace string
	Name      string
}

func (q *Queries) TemplateExists(ctx context.Context, arg TemplateExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, templateExists, arg.Namespace, arg.Name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertTemplate = `-- name: UpsertTemplate :exec
INSERT INTO templates (namespace, name, content, created_at, updated_at)
VALUES (?, ?, ?, datetime('now'), datetime('now'))
ON CONFLICT (namespace, name) DO UPDATE SET content    = excluded.content,
                                            updated_at = datetime('now')
`

type UpsertTemplateParams struct {
	Namespace string
	Name      string
	Content   []byte
}

func (q *Queries) UpsertTemplate(ctx context.Context, arg UpsertTemplateParams) error {
	_, err := q.db.ExecContext(ctx, upsertTemplate, arg.Namespace, arg.Name, arg.Content)
	return err
}
