// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mydb

import (
	"time"
)

type GasTemplate struct {
	ID        int64
	Namespace string
	Name      string
	Content   []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}
