// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pgdb

import (
	"context"
)

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE
FROM __gas_templates
WHERE namespace = $1
  AND name = $2
`

type DeleteTemplateParams struct {
	Namespace string
	Name      string
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg *DeleteTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTemplate, arg.Namespace, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTemplateContent = `-- name: GetTemplateContent :one
SELECT content
FROM __gas_templates
WHERE namespace = $1
  AND name = $2
`

type GetTemplateContentParams struct {
	Namespace string
	Name      string
}

func (q *Queries) GetTemplateContent(ctx context.Context, arg *GetTemplateContentParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getTemplateContent, arg.Namespace, arg.Name)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT name
FROM __gas_templates
WHERE namespace = $1
ORDER BY name
`

func (q *Queries) ListTemplates(ctx context.Context, namespace string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const templateExists = `-- name: TemplateExists :one
SELECT EXISTS (SELECT 1 FROM __gas_templates WHERE namespace = $1 AND name = $2)
`

type TemplateExistsParams struct {
	Namespace string
	Name      string
}

func (q *Queries) TemplateExists(ctx context.Context, arg *TemplateExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, templateExists, arg.Namespace, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertTemplate = `-- name: UpsertTemplate :exec
INSERT INTO __gas_templates (namespace, name, content, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (namespace, name) DO UPDATE SET content    = $3,
                                            updated_at = NOW()
`

type UpsertTemplateParams struct {
	Namespace string
	Name      string
	Content   []byte
}

func (q *Queries) UpsertTemplate(ctx context.Context, arg *UpsertTemplateParams) error {
	_, err := q.db.ExecContext(ctx, upsertTemplate, arg.Namespace, arg.Name, arg.Content)
	return err
}
